### ISSUE TITLE
where to find the corresponding tensorflow code

### ISSUE THREAD

**Issue by amiltonwong** [sjchoi86/dl_tutorials_4th#1]
Hi, @sjchoi86 ,

Thank you so much for organizing such a great materials on DL+TF. For the corresponding tensorflow code (listed under TensorFlow coding in syllabus.xlsx), where could we download them?

Thanks!

**Comment by sjchoi86** [comment]
Hi!
Thank you for your interest in my github.
All the implementation can be found in
https://github.com/sjchoi86/Tensorflow-101.
The name of the code is inside the parenthesis of the name of the
powerpoint files.

Best regards,
Sungjoon.


2016-12-06 10:29 GMT+09:00 amiltonwong <notifications@github.com>:

**Comment by amiltonwong** [comment]
Got it, Thanks :)
